language: node_js
install: skip
script: 'true'
deploy:
    provider: elasticbeanstalk
    access_key_id: AKIATBGGNC5JZM3XM2MK
    secret_access_key:
        secure: r53h93JSoO8uN5DU89rB0bCFoNAP5+3HarPCpZcuZiLk1rIOp3cwTuT0U83xZHp8S4gwKNQWglys3SGVZIk4GGikoEdsOrV1+OEp6UorboHKGBAyEvEwJamCu559JbgUUen7v/7JsTiuy59Z4rA2Pogy24NtDJRMSoUv9PFtWtC5F9YIS4JCPmaooj71GPl0DsOhDYdzvEmxrsrCIEf3NTcL0j9PtqGJUabx/a1Xyl416RRAoxsQLx7Cr/rtJtO+K8BRBQtZEnb8+2Pw1xY8y0UFoR5ptn2CsLl7Vh7tZlBTan2oIWqSINNjJc2EO4zmettcZtC2dEaf/5diFVvQxtAVUo9x+e912Z/RXMW//ujDYlOBmk7I2NBHwuZ6GbE/7EWGkWrZYEE+Fgf+zJbkPVwLrf6lklx1lCPlzURVfR/malqJSjin/l15q1uyqP2do3ZT5CPR/NKEoQ09dLAB/id+937dxlZYJ2wqjal/9uJxJJJ1bYuz07TAc95k17rCdNh+ft6y+L2Va2FHTPWLYhdtUtHXb/q/7j9GTpfBsUnSG2cZ9a69GK1bxhkvY20XftNhGAEKxK/SccNxpbFH8NpvM6xm+kcLWci00CH7Ey/8WsYkwcTQ8jbb4GrkpNCAo3pYm3j8aTdF027o4kcu6JEKk+fAAd/4yVHnedTguD4=
    region: us-east-2
    app: Discord Bot
    env: DiscordBot-env
    bucket_name: 'elasticbeanstalk-us-east-2-208722007891'
